apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-operator
  namespace: platform-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: platform-operator
  template:
    metadata:
      labels:
        app: platform-operator
    spec:
      serviceAccountName: platform-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: ghcr.io/pocrov4chan/platform-operator:v2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi
