apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.name" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.credentials.adminUsername }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.credentials.adminPassword }}
