{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "postgres.name" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "postgres.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "postgres.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
