---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy
  namespace: lab-canary
spec:
  encryptedData:
    client-secret: AgBxojlmvTPxz1BHZeyM49bk/vGkDtwMFr+ab8MAy2V1i5aESHtcz6vJxIRCLTmeoXT4W5Je6rKcbHTPoaBzeTwB/VVh/Ng+ch0dYHx8zq7doFFZ/S1dQk+ro7ce3y0atFjRlvDOeqoOQHZSxM7zymaZpx9H/w9IwQDsVC62MFHxaQ99Q4Wfxd+DOZIhifWKf4FVucRocgyvJtkOGm2u41eXDxPePAGqQSP4tFsQDP6Nb80lPMyc6XbRKqHTZaO1MFo/IR9IEPY9r0FVM3735/WQFVVJwJtIwePuq3+ZlSVGCK/h9svuiTLFwCxgBnWXrX5qNWgTxtj9UPuQkVv3j/O7thlVAea3RMOQddBjILOB/NzxrHtWY5Rc0dQm92FSrqQFUkwNH+Q3N7N/tHPAK7v720w+0BcTKYvOJxx2qAneF2YVTcSnMfeMHgHemzoQIH1f1n90jHaMzxp/bUJNWM61k6XONRY88tS+ebUeLrfKyWeMJwALHB6cxOa53rJ9go203AM+22Ep4ryIn3ZjGJkbgjhrCmg5QJCyaM9CS6fEDGAE76L9akczk/a34kNaebDz569B1y+5zbsemEEMhn5Rx+ei17GT/xcvUkJHFRE7NbSypnnbbSOuHmiXwrszNwYqrx8FZfdLPveeLjjcvtGzmMxaxky0f4rKaosT0R4BUf1ZafergE2zjtyeQY9BXDiFwzwok5TsohivZBYwqM78y1OZyvqZDmYlLX9jOJS6pg==
    cookie-secret: AgCQFn8O/5UU9U05YU7/6H7yHIemzvoUVSN0LHZycB3vX8VSAmbmu9zmgtdF3XpL9VTir8zeGSRs5vDAttipWA/NoIEFa9PPIaszMVixZlMYZuMl0lOSCGeU+n4qiTfw2k1nm/3mDTmZP3YRztDZ52A4yMJF/OzV7OJOMKe9FKHSSATnMuq/ToiPkfVXnBEE7HUjqjZSwlWmHLcU4eZk+Cr42eDV1+JtXys6EXMTfoV1Ia9C9sqVyarGOKLBEW1oLP3rWD5aFP8V4ml9rnbEFcLWffHPojoW+j5QhrM7nrtIkVmqFuqxohj6eUFmUkJFu7mA15aT9n9aMGDbOT/kwpUadITFrtxQRXLAdgEq6O69z9hOe8zy9Ssb+leN72AERGvAv/XlCWVBqKLCXtVhj2S27A3owbmmq9yoqWhEBlE7eF19WZ11J2Gf+D6eTc3KT5s8uKLPGXHQvGJE+a1pYa6yb8KtcbDuTFaiDIJy99Ld31JvWl2WI3rtXiFNDm9IY1cD8gFzcObzKRyj4tqFMbvoZsrVHQMEuDXOVEsxJR5leTVCzPo4W945v9RppVPrLe7Muf0bstFAE+yCII7X/efT6156qoSXXEpd+ZLOR/SUSQFMFatRpfqWS354TLOU00HLoPTCC+RPb/EHSq4XRjxmupTsaM2Ekyflvxkh/iUboyEMsIxjbRa9dx0L3zPPZ4x3fD4aHC9waOBNMg8IKns6CoYLw0ommnSjuNyholJP1A==
  template:
    metadata:
      name: oauth2-proxy
      namespace: lab-canary
    type: Opaque
