---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helm-app-keycloak
  namespace: keycloak-app
spec:
  encryptedData:
    KC_BOOTSTRAP_ADMIN_PASSWORD: AgAD9+KYXkVWAbF9xKtoJ0/GTB/TpQjbvvkIN0cA9AQKg0oWrK11RXhbikOeYQsk2bI1e/pmdkwPIeixuAc8VTbeiwiQ4zgO6SgtFUpXZ3BeDasMfSSKLNd23pIhyuFp/r1Rrla7kCUwsz8a4oIiyUQCUqH0SyURt+ii9HT4jX9DVJQA/8/ro3EQsVB2THacR+oGi67ag0dA8uFS7dyhrBQ26ZiZ3uHSEd3vs69yL2Js4M599sE30K02MzFYcXdfdmub1hAeuV+7KjKjr0ZS9bUmhgl5YDZnvKpWImpKK3qR+lB6lETbvzh8k3rhrDw7pOZTW5/yR5Lc81AtJz+vCPH3j4AnYn/HAIc9AK+DTKabtV/WOPli0aN8LcMFqLOLZNKi9KAh6denWV9v1HbOMhoq9Z6ZjN2GhlWofvk4nC/JgD+czstEnGQbuU3uEOioSjFPXH8HgocuK2F8ngFFkqVx/jLRF2rKGTGzDVLgnsEO3jLZHjS4YJ6CV7rykobW+XpI8UgBWijsf91Ha8vnN32cNGKL8qGj2ozAIX5o0+jydPefH8emdmXYkI8kqMz9mwgDiDMyAll7gfVjlNLuILftoA/CpRk24n5SMu1GutGvF2Bptdvs/4iyYxSnZv3CvXP0iHfTv2NOoU5toL8gOSpo4gUSpyz7EDoiSoKTk36yvhY2qWrqHtbwSCIxZHfM5KdtBMvL5k1QZ+ZUj/NHqHtLDwiDpG5/ipBD7EKrYh4piK+/JQE=
    KC_BOOTSTRAP_ADMIN_USERNAME: AgCJaNrsH4NkXabayoHvTLUBvYcfCmm1hOlEnwSAEAnR9fYPiKbKG7TBUEBJ5Dv1b+AEtsd6poOwr+MolKLX62q/rijzm0lkr+pTXm/Wcd2TotDFypqxz1pXJgrX8q3ENS3vKkeJfxaHoJXWMzZVZczfutGRQpXzcwbV9Eeh2yG1xX5NAefOY0d72TiJR6XWEDmK/YP9wJz1ZcH/u59h4r+K/lajkSFmB7m9B3xX5bHJO4Mtdm+qfafIV4N31b+4niUPMOCl8AhDAdl0SKMjT8a8sp2RC2/Se3RJru1Km/B5ZDoewo5o8aXx6vitqDxecxsU0oHnC005IyjKAKRaFm2A1VS8lkNHU36vR+GFL5k2a351yPy+7JjelwPRcKv1zP8vFNFdKHVkLNrZLYqdMn99xgHHsdBNLiwtYA3crCnusCYqlIcVv0F6eSujXjA54+1VEt0z7KJJdUY2PLHIrzI13yM2Bu9t1Osha2poqqqlPN5NKj7bbEAvc2g861YEqYYI7jWmaL0d/M8aao7zS2XsOYzf+E8BfN3nf0qwoR3RTR/Af/1N+S4Yj65qlijn0U8XxBYh/6WTJaIbWX7a1PVuCFA96F59qYVCA8xqSlFE4axv7xNUA8xAC8LNBt4Kgxv4apwBCGfri288K3RtQGSHfSilflF/DpXSwGaPjZY+cNaZdhBCA45jYuJGv36pEBv5isWF3Q==
  template:
    metadata:
      name: helm-app-keycloak
      namespace: keycloak-app
    type: Opaque
