---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgATjzhDy2yOa7qznPmdqHWLN0n4suXr/9riHm+6DUedsDzXrNYLwro0qgSW4IsDxZtmlUGyniB3nDnuQWM1dlJidxJhz3I5c2xD1LCBW98GmxRpAQHQqQVEK5wiqrX4VerxnamVxGmRPPS1E5fMF0mEoJAqne4eszNX0kgkt+0jrBO4d9U7Qx0bPiUzwf7MEO+BM3DcQ+LYEqkW6wlTtJ49BIMmhz/KnlYpFUrmjykQe19IjUq7mq9R1GXEbPSfPRYXuK8ieMR3c+JwHwOdweJqrGhDIp4xybiY7/pczqsD6m606y1Y0IJ/6vYNS/F47OYETjovemyAa7DWNc0AvxKRNHj09stNxcgxgivC2p4YlXDpniMuBqZx7CnPTJM+dx3YLzKLKUxH3Ud6LxvYmVggy35DxRLKVXvQx0MnurwiWF21Fh+V7xapZCrCOmqhvdhxzIrB5MHL/PDZ3wkDsCrv1byx9fEaBuPpkl4pJzLaG3YJvP+5TLfSNw/pQzFMdt8q1bpFRUZWaMHsFbd8DlpnVFtzmgFD2tnDhCzF6wof0c94aVACTy6WPvqX8wUFK1LVjl5AxsKzsnP3Vs//A30tDvWg7hFQgKo0Bm2x8YmgqGjVArNfHf3PEs4bW0p9nWcAGMjHXD8y1qY0kEVKT3U3AdnoyzoxVHkyN9vAgtHwy7+IPNNdDC7J2kv3Rx6P9iLqfmcEwSBnWBfs7E4cclC2uc+NbkeQWTMgY/XptAShlKPwGBg=
    admin-user: AgBK6N3s+bz6sM4gzVRn1yQbIQaTSkol5uDrc6vHRrFTbFW6SpDetvFU4JF7aNVWQsUOlt0P4sfWO8B1xVj3b5YLT7nRsnhK0SmdNOxz8yX+VeGvyyw+2QXBbInFZsEse2CkXL1+vn6gMLUFCCKQqec3rwQSTRHuZMEPfFwFUQnKvGnN0JsgYRm3LB1P3H0Qb6a1IIUREtHSv5f6EqpybeuAXJkoFCg8zifVYMDti86Yc/sYOulPcITN0PYmatPz38EPtbHqEQNyNgd+d9DzqgjzvDYXnu+yBpAMxVdoxAQ1r0jocvptSW5wftkRQlzcYLMvkwNV3To2Lvge0v1PquXaC0VX/mViIQraOZb/c0j1a9mKN+YF6luufPIIgRB5HU9Pn3OXoe2laCLfzygvgEVImN5DZIoXvkIIbfanLxO6FMTYgq9NeULosi3ZWFzBp5ixSoF88+evKV4i8VrbPFkXwj/WZLLFsN3fJYKUv/uGv/5BdkASS+HyD9RG4OGwOc8YnqiRwbvDl5H3cqKO4JNcQFe+qGTq5mV2ohNsM1D72Jt+eFE8/0+oLQai1sy0F4dKhwocbzly7MJ9GoKX1Kh6ZKag2UZRvsTWqNIqwvwauHUOaYu72/kbiaElsG01grOO7XWJneFL82LfxmoV6rs1CbMoci8uLRNNydrFbkxjeHNGxD9kZehlRuV06NfhKn+d49zc6A==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
