---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy
  namespace: lab-canary
spec:
  encryptedData:
    client-secret: AgBf2EeQJTa9VZejSLPNpcdRqvxe0Ufw7vkMhtZJi26Sr6Hxo9ONi7WzNUP/L3Nr0dkwwqff9N6XJ2xl+lvly+gJ5YdOE44rcAvUdY78qPtYM+S4R1mFWmT1vOfJlEEOx3Tic368hwK65MCwbVOzK8R/6//hJZiRR9l+M9E3NN1ig6qAJ8QDC4gq5Fkf7m8eThOe3xX44nm2oyQKPMw+kO4Sr48+HblPLN38iN1n8GhSb6fVLS3gc0veIS9QttnoeZfXreGHRBHodAgM6lXY9d942yQMEcV00BMY7BNCsb5YjihMbANFTcVS4hPoSm5jgPSjqMlNA9U07vk2EyBXV7NKobTaS/hmNYpLkelGCqVel+raycuudNpwXZrSNALfjzXxJVYdRVuSB5aE8lKYqfXZg5XqKfItyJ4za4bYGRMUBstylzu6nekc55cvsXN6QYfVSakedTkowRZNw9QhpBSBbKcpbnGv8H2nUV17v02PdRSEeCI6xNFJ2rGS29h3kIf1Z+NobJo/XGVEI4jOaZqv8MTopzLBl6jSLDRoqBvoBf11MV3HSAz9iLM8YogOf5kq/cmkF+2ujB77o2DYqUvKYuvwZiX/w/eL0/aZcHX3FBDGzOJE494UGmGh1opqlgmfjJuRKIIu0Kh/kynk3etEWAcnU3wqAR4tf1PB7FF9pD5iH9wL2S9Y1Al2l7SHznF2gNZ3BT8oWfgI7V9rQ3Ux/SkaXzLHkwPQWvUHhOHjZA==
    cookie-secret: AgBmKeVktggWMdGDdaW4MGPf33NPqlK6OHoMyx4PbB+QFEdwBFki29Dc90UK6wJT/R7VNQS1pLVDAD3mQjd7V/BbgG4b0I1ZPobRb6RwZQ+XnxvdUKEw3owZ+VXO7hTK4yGIdry3Q9CQgwwAVyWDsyyNjE2OFyrDaz4VF/gRezEBsrOQW2S9UDmU93PAfV+uWYgwdF+LMEnLq1DEIjyEZvPHS3gWiQ7QIPWNbvHUUd/+EnVyTyJaOhP6R2WEy36XY/4N1D1rxQ3xs3h31u/KBCot704Ru9CLuoZF3KwHJokW05XBgqEZMuojWO728iPCGNS6EJKrGLWj5xXfmEVbQBnWhXVoYUmYZtry2TrDujpKaVzhr51HTGP5Qvzp2Tcr0q1xhXaeQODPGGyBunJydsl+a2uLlC0se1l+RMle/vK/3XE3MrKsQ8yuCzbG1iCFmFCnLpCtcQa46+NmZf1S/ep8rCwt3HpS1SnRCbygZj6deRT6n8ghOsRARRMJittfWqs8TcBmUsTUlj+MiAXRTnt1s34aBPLxsS7yYeTyMXcFxUrkeYcagrxLDWEpHmMYKNaCzF4bDOlirBAiS3vul+LksIQOainIO3wK13K+BXptEGywnwp8Bpx1x20TV8DOUkimuSWq0Ef3rXXK/abgDU2t3VrW+OX/tXZoNLiIAKI+8hXLfkgc+WshvIWPONtVUgmFmrpCe4kODvl4zRm7/P+T1euWaDSQRNLc3vw/FXOvFw==
  template:
    metadata:
      name: oauth2-proxy
      namespace: lab-canary
    type: Opaque
