---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCXSgdnXReKZMZnHLeTkxwl5CeIQ6RysIkPB6tL/KCteVDrjBiHnk5mlZD9rjHkm/UFSovsqzasTORIbFf873ujrexcxr+++5kcbWUHwUpbxyS+2a5GjT2/rvuoSKM10RSi4GldCfM47fROVPzBiME76yhJrlriBL+pZ7JEloRTo+LRoQeMRaxe7tP/W6bdf9nLhCdrM82n49/WKnKbTnL4MHbqdkcO6CvdFPB72oCVvit8dSXt6MCgSP5JpwaCepd9+dzy4TnQ8iYyWr/8gRv79wMuM5RGL2e+qcY83yhPXbUcTeFB4sLxI07A2qGiPYt9ziwUYlQ1msX0IWXyEhaHtPLtkIIZUvYmV9Ly6dvQ/yEK3cuTkQPBkFVaV/31FPJBugliEopD5nE6PVO/x0Ogi09avywLRd64qriWVan4iAy9n6GeQ/kZJENiLAmMR/ET733Olm/EaSP3fMnXz09lrmwFDHcdZM5t1j2rdErbM7+CRFwIxaqr6pAn8X7BTl2nibzC5hlWpMOtGed1GCdjPQ6WE6Rmouo03V2uv8nIS1X3umcPcZTx7IWfh8G3ZBlZgpdaqUgNe6HiMjlh3rZcvgN6caDJ5Lh5N0QRaoWzAmotUESmbN7O6HaVTmqyF7ds6jkUJ6N2cmGGN24mz93d0SqI53vj4mP7TmxQA4TXMsCF+Ss1P7CCgEKHOt+CS+I/lPS2j/ltoPlhsUIg
    rootUser: AgCik4wJHPrNhuN0q+pzQtR5z5SzKTT7dvQKAuhqBKUoUOnlbHRZCN3R7Xrfi8Ig0AMZZY3hQLjD1jwOjfwwfp5nBlcnd+SRTbJJ18ayx7StSGTu0d5EHKhfQNILDCcboXrI42X+f+vlrnlzx/o9SXVQaNOBYfZArN3jPjVzmXpEugqks0mhb6zBegpFa5qGchESEcjButz24Ffxep1vB4L6UcJSqEyFYGv2LocwBg2F3csmCvifIc7hhkwiKDlwItB7oEfxRL9+/quOwoxvGmmf2oLsGRazgDRESU43tF73+i0NRRDFF+AkBQNDVXU05EoxDkEM4FsbpET9Cc2G2uJlA+G6H5SBoZdfnsmycyFyg4hUx66b15ZnjWbpDt8uFEnxN2OpKYAcoXS6Oqn7NUpsJK5sGn9q/rcEKc3d6235AQlLPaHEHeX35th9F58QWQWrzQk4plS6VtqJBWFCj2/valOv5Bz+UMaGfjXKf4Ngz2JF/9PJY7kJq9chIrv2sPaxK5NItNWTLnPbkc0pDGKeqBekiiYciYN3nHzrfNNRTuD+2X2g2I0B29Wv4Si6kXh8iLC8jw8DcU4wgnDZKjTqglD/fgloCziLMxL2gnFahX2VLmiRak8VwJWcbQq+iISSgkWbLK2ESvLAb7Xdjgpiy/oEm30mYwbL15n6267mBuYTShsies8Wzw2V5tuZx6Z/Xa7rMlRfXc1G
  template:
    metadata:
      name: minio-creds
      namespace: minio
    type: Opaque
