---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgAkyybyCiN22omoeR0FXWqa2IGSfyGtF0Xwus6PX/cC3d8sJxLxmnUf2K32nRJVYsCNBdUaO826/IvRaACCHR951WEL4kOE/YbPpLg4bfNpTgnPuwgO/qMAR8WKbY6lAaHhjyQLe+azT79JSdNp+eJSvIO4+4R+rItz2Na1AU76fLnvdWfp7SdPYHWlz2GK13l5vayC+ELKZjakL7HhAInUbtsgeg7v0P7Lia1v0B4bchX/1N0AYLufHE5q1CUjC02FqXDEh3WDnmP+1ASzpKQntr3ZZ4ed2FqRPmMgja9YLoOGfExSuB+rq2M22h5YV8qYxEOUIVtbk9uBkXR7ZQ3iKlrCiYXhrj1Tz3L7WBIcQ9AMGquly59rJPJRgo5VNfeMv9N5cOJKDe+N2oINidGaRd/Qpy47BaXLjVLEScDv+gOSVpVCIY2beT/l9j0uXuf9dArJuerW99vwZ66a5GMvq8YGeZ7u+YRGyHfq9uRs/Ph7nMARhybQmJ2xTBTsjvpOK4lPAxjbVA6/QGJ2NsBjRq3CPpeEFt+Rg8rj6ephr8+7Ny96mxIWUAoWN8FhNCfr7/LLn7ng62o5ADLhkvdx6BssTqWO7T12DcSC2VQ5my2Acnm6ncy4lAtWaDyoKahlok/Byg9h8qr7oG4Z/juZ6T1VDjeFw5oLicWHDqO0xuXtvwAwqak8DTARfg2Zxevfl5+givtBx34sONhO
    rootUser: AgBN3VZw6MTNmishVhI+1ygsHncNU8mNxrs1mRYR91fw/iB0f+btfIt6tqqWZugluK+Xd3w8BASWRQDLbljsmHy8BIh5zOYNPELj+FVS6CV2wnnOqdKcAAqHx+1W9hcbEjeAq0lymOUqiN0LJlZIYkh5RHnStwgVJC2Uwq8Nc7Ljce8czWFei1ZlSivcVJAOt2groVSmxGhwCEmFnb20V5F8D0DaCEZkElRTLqbco16EnVobvctBb5zWupdVkcW8l3wHEJHg4q+WUbB5o/Mb6ivnR7BCFrdCtZX8y3t99QwNWRzLFda1c5pGk992QB55BgIQmZsehKnmqeZgIz5LEqNe7jAEpN8rJDYSnjbd69mcfIpX4mdbYTdhj0RJ5vzfz1wZaX0EOe534Vkc7V6VRP77LyhmbWEBhBKae/tQrPFGCXx/+EKMlxhcuzUB59LzRc4x8hJMFcObn6AzyjIyvlZUoz4MeNtGHEyAACOQ7b++g0AirtL7grcsy0qfyJ1yen1tflAMKKvTHPDl1VDavhLGX7UBjJJpdJ01IBrTu5pAWRO1E5G1wypX7Mf91xiMRqdVSRTfMLUuD/v95VXabTb9uf/PCskRjS2o4D/weKNQ6OkDMeaV9PrmzWc0vMUV8Es10RdvpNHkYX5KALvzrCvylPy/pykHFuvDCA5IrhOwI+9TQgzTV1RB1BfM0xSMDuf1lAgm0yph1b/u
  template:
    metadata:
      name: minio-creds
      namespace: minio
    type: Opaque
