---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAi2meflbSdycY4BOzffReHZL/kT/t0nQqt06nL/GNQ8Q1pvM9m9LEteQwkfy0uqZ8Lao9czl835f5mpTS2NSl6sZ5QQaPtoV5+Vn3d+9wob4k4XfkeHFttqfFw6lVOMm9/hJ6qP3Dj0CzWVw2UcWsOC6xIU99HmF7x8EUaDCp5M3MI3eTNGgSOuUFM9mSM3EaIK0E5TVNqqBbDERRQiEsGa1I3tyWM2CxBenjPAAOI0UAElP3o5rP+0WXims5RDupx1TYcE7lElrBhSJ5gMa9AITyCY4omqC9wndYu0+HSl7jumcm8h0CmJzQb8Ok/iFUFxkheoCMb5qhGlygvl/Vj8UCzupk3LlahQGzypG2ROYYOV5mfD1zqS80hPhYSiFlI+36LU21Mr+6Kk+VO2PBMSpVoRgwitWLsomdr0JSHx0oj1dlvYnUAGwc5qrqn3NlQD8Kcyww13szyTGwbuu3qkNy1Qu/5BwQfCpVer+vBW+b6tGLA8fIAF2Hz5iQ35Z7XpufFqLcPckzEeRs9HFUACpb9IcztbBhUDkAxlGZSURjK8JrFKzDlZD9DppcabgifZr7vmMEyFlcslnIDiqZalT1Y02em1ipz9l7qi9Vy1WLJfdErW98ZVAHKbqfE626Qe7WWbNfopt0TPa905DmmYBa949u9BX0W7e48x5ddrKEqnpm8qIsAmcmuW2M8jGeixAfe83It4IfyDY42zt9erwI5n5o/2ctrMFk6e+5GujKAF1c=
    admin-user: AgCYb3LuF6KRHvbMERD7s+iOIxe8wQWh2u09kGt3vJFmefmLISPCSU8nQdoZ2/g5W2anwF8LvG8g/D5FSVFqAyH4cpePZldP6kpxJ4QqrZ+tAH/vN96PSOo7BnvNt/xuClaO/Lnr+FV1C+srZ7cG79JjqbFPHplljdO1kuwgk5zlUXohZHqN7d/rmKP2w454IKpuP82vOhGBxJ18SsRJArZAVgijCQRL0ZzWXRzcsVJFy48kNXy+a6IWB8uWsuigy/EkUQbHOOhZbbEw6O0RsNzXGotmhCpMvMkakXEdQhwdi158VdeZj5ZTLSEZZ9k8tlIYMDmULK5VCVTtlU0AGiazsxnm6mxVgUaq2q7lraOfZRzVOu2u5RCnUTgO1USXCobJmFwwvDp3CLmo6YhA4tGWfuyJzXcgH1GaiKX79PtFW6lCus9uQvy2HGvs+Ze1/rGthuHa9Dh70OpF1K5/8A8WTojkAkf3dW2Rvf/zhgsegw/h/IfzQb7/8cBbgfbujLo7BkzGF06s8BxGwD8v7oErbbgXBzjUnV0T5cRsuUP5tv57wdOgi7WkCrp7fXO1r7S0HgSWY96/bS3+Vcw+9mIFm58rbec1Plc4UrAf9bbm88ULjzVzvko9NVdqc0iRIxNprztSgoDOYIP6RdMnsBEo1c+HOYDeV45yEEw02jkebiXpf4hrMVQW7bRRwrvyw0zNqzsE6A==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
