---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCnkCn/7c1yzXAltjtfdovuw1QAI1YPxudCXgU5VpbFT/KkNICRRW5GlObn01XS6SSoaOnTiMQCJFihEvW7GtRu2CXJy7ZLhgaBiMacKzTUc+zbYn7dt9DaxZfgXA3W6xG6W2hVQZgqNPzgY1KS2YfP3rtQAN1oGODwC5YW3tOpDOrBPQBfxBQqYmKcJ5z9C0fMGSijtuNQuJp39R5MSwmCkll7LmLgq5Qda3v8w0XHHA7k4iwDu+WFaONxmPZttLw5aEHDmNOMB4GddkMB3DXcoWz42vLhgNi4eUYKX+PU2aFDws+Iu2YpVKYq/Q9U8dy/fHIRqY+key2io5giNU1Tc/l19rpwjGwvOzQuOH7WpvJuDDvEUO/yz+KXp5XgN3f5DX1zMMM0Xr4FP0dIWl+TBD9ccr/11Qvs6R/eJe//hPnYRgLgcZ20YulSb27ydv14FPkqfCvtNtuqSjtwbm5O+S/17iGV9sYSUnSS0IxVLMZTYq1q6ksvl7ygrWmfHrQZZ6v/Iu9zRuTejJKy3VK1tyCtGmx/KDJeIVqQ73V+b2MtS2LDcWVtt/mhrJwJvOyLgVFwBQZsu6IaZuPDODUQXdA36f39PS2291dfOBgwfeht38SUD/tovkI3na2zx31XKocsXJMWbg0Jwp+/KTCkk3hmP1ZDsljWOrrSek6/9i3Dnb7VoYyVqrToHZvGZjlulJv3/+3hScPaP/Xpo68tjVVvWUdHrY2mHvf+vTQZrj2BOVs=
    admin-user: AgCMaIx6D4iPzyEWNkv4nTNzqevJudAdGXIF7pwG5Hqi0H07LBDp3fuT9eKBd4+trdLkwOPSt7/G1klyzcyssJubUXpoT2v4Nc96Cvdijkzk7ih+6nWeLzFTSRqOEZnJ9J4FjXRHo1BDa8kwqbm49t9RzFtimqkIEQs7rkMSMgREomXVBwkrMq1rkP1pIYcmP6cuXAWPpNTCPFbvbx+RwLHCv9i5AN3xQP3twxwIHFvf84G2pTGwr42QcNWHW6lYP394/2eT6snjwMjF6rR97qxfnmLIT2/ZDO0PWdu5x7oX9CvW3Ug5fzIV1lvRWkttX1zdJvvaFohefeC0s/vIszQGSkbdCtcha0lk91Opu9/qp9SDuD3i9OvoHsmMmRpEXmmDYtbZcGrSgdT39YakJQDnwGAbLq+gt1TFrPOLLOTAsjRs/9+OnP3fzWbfgQQmi6R+rr+z9baymSP8kLarh8wH1vPsfTgxvHuGzjs32PiDzwZBB8vtNmkMuvVeFOdF2+A0GnBlWpvOvrGZEXF14DgkZjXbX2TDh4fVtRttDHU+poVP0foksI031eHn1Vy63Z6ejtEcgwxwce358O56JuZ4fVoWfbVh6w+eiOZXPkJ/fxGSt2CvKl+RwFe1haDjl3QKHTHqzzyugMmErWcXtQhIrKjB3pL6o+9BtnlQDZj5HZp0gP/1Rb6/nVKQ8xLFQZDvTMCEfw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
