---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helm-app-keycloak
  namespace: keycloak-app
spec:
  encryptedData:
    KC_BOOTSTRAP_ADMIN_PASSWORD: AgA7Uq22KygX/6q9EtPT8T9MVYgLyXiJ3crs6UohG2+tolEry8J92Saojt2GO0EdyNOtiDxfXoiBpFkDdFr402hyVvYa8b76O1N896HOXkWIGf2QXfqdaJ3w1pcp6g164sDlNp/EsX766YFAhWrnVkUGhwq5JGGG7Fnx9RPWG50bwdL6qJfPK3r0OgUau6N7cmxiTcxDAaQKYwQ07Fetf48inPTUrx91qRDTFpvguSrZ4GJrGo/9REpPylAxpH4FEfNUIrhNILCfA/iQ/FzGWTTxNBN6UNOopogb0ropQI52r7xdkQebrz9vEWS8hPII1rZs57+Fp7UoxE+VIAtjdE02Ppsk91ZD2w1q0fPISORF5hcbXlR60fLaC8LOFGZLAxpr/yu1Fy0l20BLEscQh8JCVXvXGV+dJ87P3HfdV+gveJQmOfAZI3tQajL34VWRKaZq54lX4TnMCFG7qDVc2oa2lp6W5cGvAEhqHL/4YS39PV4gHeAwwuuTvwFrXPG21A8MknxplaBi2MzdWcQ72ZCQyOshPuie+3C12EA3O052zxIyb0jCMvGDcdvoUnfpHbJ7xFfISMeXmy1TYDNdkyPxOVet+88ukYqr/gpSrk4S3hMveSbUj942BJ+7/ZRWPX4kUgy3CALvhAA30noTmmACZCwBtpKfQKPpRXOdUFsyEXQNWmfzS4XcZFJc5EGd0hX2RumEbCqcDqueBEPtkIaIu5V/nU/v9A1aHL2l8Z9+U0wYP38=
    KC_BOOTSTRAP_ADMIN_USERNAME: AgAZYAy90xsY2va7VpAqGussOf+8RNL3CEDWc8wBRhOh6jZzB1kiN3JZQpgFHx8ATnCxQVapn0Iwz+VdSvvCg86Z+tvzrcrHSzFUoGbMjewdO01aEHonWQEduV9Fdj/ozEoyzp6Jg8m3+KL/x1k+2fLo0bX2lG9YTdnrXA1KEreh1gHKQm9ubK9gUYEL5GB2efMZKsKdsTi9dcvOVigDZVK+LlVXHdgT2ZhVLel+g+EEBBzGYfEYzUzf4sVDsSPCDTPQIu717I4br2A9JSzhlsbUKr2ir9QKTopX6amO/h48gUAszmzOoNJ+g/EAadEnYNUUyE8tdJtAd63wKaVL0cPKDaRndTYupr/CeejAWhSYHqNaIhPcJnyyGxryUo+Oj7+9WQCHK6aAQIuo4aVvRnW5PcvVlOaZGq9fzss625ECoYejI5pxyXsvzoi00216QmGoXsedoTe/AiUW/reNdS98/iRuhqaYbCFJrrDJ/8do7vs9eS6y6+YQI2n/0KxgS8x/EWKDlZEROPKAzY1QuqJptIi00OBDZ6mymaFITKvRZbxVp6yGd3+xm+HHsMru06nrotFoyr+bHWCtbNwUDWdlrNGgp9MXrOAiFy78im9g3k9gAgUnclvrF94UzBYSERwhce2eR4fDjxz5iOt11xqNgpiGIQaFwWKfcZRVuq6qtqdpYSkrgR8iX4DnuXK8aCtAFIW3uA==
  template:
    metadata:
      name: helm-app-keycloak
      namespace: keycloak-app
    type: Opaque
