---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    client-secret: AgCpL359MrwLeRehDBmUBZ9DHUXnjCrJkE0hDnVepkexTcWnRtY+nK0Ru2sowQKlBLM2KeJ6QUJM2BiWeMzBoIgqA/tT1TY8IDSEkpt0Th5ihZcd8hlNVu5ztM6ZLkUtssZihFE/FLP6IAVKag05ELEA5ZQt3HI5bsA9k82Wwqt4fOXM/DRi5heFClkSbN8K0cNcdC9LzyQxgPgqmz5SUkLedYt06NSElr6Gsdw+KlYw2i4Xxx+uwwsK2HOkL+cg4DWEyOCC00egw0A7aaGw+YZMx3GJf0rT18yDwrX5m11FAEgmYTmOTa3cCZqcu5N6Ym7+gDb0tcTL2howlzhPmIfWofgxCPhn2JBIHX/vm8BZKmUXwxPxCBdHEk/f7Qs/gCFRVO1Yi/pOSdXsvY2NAoIxOfl7okbtbQ1CqF7OQU2BW++CNXUXz2y4gLnc2lY6ElwjaBHdwzKlCH3/27bXLKX3cLvjOeBGwQgL2X5nailTSDcpktomkmhnRNZd0JTV+VlHDsq5rf/I26OdQITJ1M+0kuqC0cWwL+ZoxFb+zrMORZB9mca7xVM8SYrO5PFAlsCdNZ5nm7voitBoyjYYjAiret47Er2mGwwbgIpXrBLFloupuZJPtQUDfo0anHp5wzWHyFfTrqs4e14+gxrikUvK+R6xzjKONSkJz3YuzFELxJMfdlvgapsea+eg62CtngP8pEwsH0L+tWfFy/PxJtHymJdfEBmCLbffbs3WaQRdrw==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
    type: Opaque
