---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgAjBsIL61V9WxbdU8yjE+t7asdUY1fxztpm2VCsvdmgbIqtUygEJnItQE6yBZFEi08nQGMr06V1eIOJ8KA3BDQZslLemWF2+q4idu+Mz0pAwltuhMUq208r4Led2zfjkHCFxsKp7PcJri6hLhFKjNdV7pnTMN+oKLESxk8hVSOVKKumsg0za8gI00b4gnwmo3xJ2FwgOUln4y7RIBkUFYJRBeFKtxWel05X8H5ZoOABtvCldyppWtWGYYNCBYSOgpz36jNYfmLtGHzehmEvJBtZ3Be5OeDR7HpJ0jdAcq98jFbnf8Ra/6YJgQvtx33voA0Boh6b5IViqg/2wPNYH+bBBL2wGF8YtydtShrfoUDGOxw8Dsd/GAfj88UjGRj94CF3bxuxPuUNAOsgwItF+QV/o19Ds6tlK+QHdr4qYs/+cUTXP+KnoUofEXCqoXByq5abk9GoQz5+TjP1zibVolf7330Ppd8/JlexMpqS4vSB9zxkQroNxT+nvIKFGFn0IsscTpJ1sA/ZbVAZjgSWgHIh5er2UjjcnDZKB6+fVy+nLM6+/eJ8I737fsFjkFyi5jlTPHbvqOzyW6g0RxdJC0KrDs8aZOOcnjllzrX6896M3PrvqSaz2RqF6KpaR0N6NqEMGCVujxhq5Rce/rHCkNyT7nCMVnuPznwftAga9649cyygdVOtuKYXr/rAN3GWIH8cTsqWCVCxaxGGMAIz
    rootUser: AgAfI4t4q2xHEEwLcgBifOLcR163bCZLXC9xPXTXKLRRq+F7tOsvEik12otnCkLIjGyFyywJ1SRZlKq7R7E/HRkaUeZj2/R5dlZAH1volAF6KWJ10bd50y47uur/zLyfsfOhUY4LCXzMrYio3vcwOX5lXeC2juma8tLJmJ8rT5VabF3gyZbXMfbEzJNOLHRSddmzIt6TmMvBB32IkUCxcEBjpkOqpRxCkuM7sId+H+T7GMAVeiiWoFwVvb98OygyitTPdjqSbJfOJYKSCps/vcJaX3rfLh6djgNx2gfb3bYA1BcyV4GDYJvy0GXNM6UTi1E51BtWq6bsUsZSG87df7/YJtSTzoT1jezyKZIAt789BLC7LZBgbGeRab1l3dr5Qegd9mZJCseDQ06tZvaczOut4tANZm2SniS1fOr0t4cwBCDIxdNSA5P20tgMngtSSrBZDJkfAeD/LXcD9OSfZoykIB6VmbS8e/n1hLxZAsA1jlZlzzTrRTTq1j3HLq7iD1+sgXh5BLjNafRsh4bLqxxqcoDfB6/ijCUSLP31UVdCGwI6r4nZ8xCseZeQElwh9PHy3vgxl9Ki3vk+HTq+hKHwe3hFa1x7xD2Cqlvb3jWnaDqQHQ0gI5pVdnqk/z3/Xac1Nkrvtsj00kkwJmD+VshS+YKklH0VeIHk+cQoM8gpV0kQFqRlVP3LGrNJf4p51X1yitMi09VzYBTU
  template:
    metadata:
      name: minio-creds
      namespace: minio
    type: Opaque
