---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helm-app-keycloak
  namespace: keycloak-app
spec:
  encryptedData:
    KC_BOOTSTRAP_ADMIN_PASSWORD: AgBjP6J+a2TGTptrB4NbBMUxu+p+VwUdc/r6pfkv4PKCa29WN0SKlZMgssPwUVPw0CA60SVjkCCZMjyY+vyBy3q/kIMelavgO9dMKfm1t0OX/G2rA6ReNZMEEdWK1TLwbLpXog1INthn5vkTyw9tMyjvaheGvCSLwRpVjHQ3PRLxsCIcM/5S51/7mC/selyPe8u7WUsH26qPJ8IkYg2b0kxcM7sTLRI37zY6mx/1EV/SlICcb3vT51ix7xKfDPi/mUxegvKcNPLfcJVHMZBdm/7jxgabBkMZEc7yZQjlZvjh/hfOKHfG70ruA14S8WLJPwA3UXRaxBIAI+ZP84l4VqLPOOwXce4FReK766hE7PZFaPnHbcE7dLFgnIDlpSZswkLeOmDXL4ZU3XH/vMEZPtaRyq3Fu4+UjKdFzyVw6vbaYCvp5pE4GintIrpU2ucH+MByrKv2H6v82mUMpgPphTJSlo8nszLmamnN2WIq0TX4+/gexIHb5HNSnxILMBBSycvoCgeAHKw9ITeEb9157bZtWwm4E5oek3wBBUuH1JwlR2HBDhSeYsI3EDBFanwPm/c16acmtP2u7AHf23Woefcy1dnwdsVEIMP/48BU8IfR+x4P5fkzlLPOV2lxQwAjJvZBoP/bmlnIYacewGZnAqojrZBTqf3JXXtUiLxSIQt4kY7raLaDAhKGc8bvzRP8ly14tMhtnCJ4zK6uLq35Y3D5B+yh/QhPaeL5/OylgBCKjVYyl6Q=
    KC_BOOTSTRAP_ADMIN_USERNAME: AgACZnYvhUqMh1YyvYzGd7EZBpbTNFn6YNZ7o5cd/Q3U3LUH3Hh5YVVeQFLuSBW1T5/TlReyzbpF/0Pd+lkKhC8fSOd2pzImRYCGX4TZM3flSZuX/SAJdbcG9HKEOVhT3Y1w10E3b7+ngT7i16qxF3ylFuLx25I+cp5fQ74ZNYGv5URORdLHg9HEPVQSPtUS3AmXfx7wviYlWZZsWcmvr0JWec7vrQCVXjE2D2NMFDU7xCNuNDluSOuT34s9Cd9peTJ/AXJqvKyVRyEALj6TRi3ge3rdan3yMpEZ7S/V2347F9nCNBrCFhlI/BrTC03glVyFcb/eyoQiEFwCl4F39vMvBw+r6s0EBTPwsJkTaJH2BDbT57W0BSkbUAXCZ2GXJ8p/o2w8Vl7uk3Ho3Vjc6KTKTKpigWDpDXWcQM+E3G7s9r2DuQuTX+On8NJc3MrRDAQ0SzXZy7AeMDBEkkd24OXnVn7iTCVBsUDxHGXCRGULSaFgYqTamPl9CsB+VGQV35zd8Ri9K3TI/9ljPpxYtz6ODSTJU9AN/zwtNV5S8eJ/Ix6pB551d302Q6MkYAR3M0j/H971RWdwyT4LRVpJS4JyJ6I9M0oBn6y0PdVplw/xk+Uk0UzOJhCxPUs0X1LsvmB2f+7ZOn78h5ank1ZxTA8NPOvy/A7R4ccagLb45SIQgIUytfEyqw4n8AplzABawIPaqQ/FoA==
  template:
    metadata:
      name: helm-app-keycloak
      namespace: keycloak-app
    type: Opaque
