image:
  repository: quay.io/keycloak/keycloak
  tag: "26.0"

replicas: 1

hostname: "https://keycloak.local"

ingress:
  enabled: true
  className: traefik
  host: keycloak.local
  tlsSecret: keycloak-tls

resources:
  requests:
    memory: "258Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "512m"

serviceAccount:
  create: true

networkPolicy:
  enabled: true
