apiVersion: v2
name: keycloak-stack
description: Umbrella chart for Keycloak + PostgreSQL stack
version: 0.1.0
type: application

dependencies:
- name: keycloak
  version: 0.1.0
  repository: file://charts/keycloak
- name: postgres
  version: 0.1.0
  repository: file://charts/postgres
