image:
  repository: postgres
  tag: "16"

replicas: 1

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

serviceAccount:
  create: true

networkPolicy:
  enabled: true
